/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Cv1AmbulanceXlList {
    }
}
declare global {
    interface HTMLCv1AmbulanceXlListElement extends Components.Cv1AmbulanceXlList, HTMLStencilElement {
    }
    var HTMLCv1AmbulanceXlListElement: {
        prototype: HTMLCv1AmbulanceXlListElement;
        new (): HTMLCv1AmbulanceXlListElement;
    };
    interface HTMLElementTagNameMap {
        "cv1-ambulance-xl-list": HTMLCv1AmbulanceXlListElement;
    }
}
declare namespace LocalJSX {
    interface Cv1AmbulanceXlList {
    }
    interface IntrinsicElements {
        "cv1-ambulance-xl-list": Cv1AmbulanceXlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cv1-ambulance-xl-list": LocalJSX.IntrinsicElements["cv1-ambulance-xl-list"] & JSXBase.HTMLAttributes<HTMLCv1AmbulanceXlListElement>;
        }
    }
}
